site_name: Tu luyện ngoại ngữ - Daihocmo
site_description: Phương pháp học mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.instant
  palette:
    primary: indigo

nav:
  - 'Home':
      - 'Khởi đầu': index.md
      - 'Động lực học': cai-thien-dong-luc.md
      - 'Tại sao cần tự học?': can-tu-hoc.md
      - 'Đừng nói và viết': 'no-output.md'
  - 'Guide':
      - 'Tự học': guide.md
      - 'Đọc': doc.md
      - 'Đầu vào (Input)': input.md
      - 'SRS': srs.md
      - 'Language Domain': language-domain.md
  - 'Lộ trình học':
      - 'Tổng hợp': 'lo-trinh-hoc.md'
  - 'FAQ':
      - 'Câu hỏi thường gặp': 'faq.md'
      - 'Học qua phim': 'phim-anh.md'
  - 'Setup':
      - 'Anki': anki.md
      - 'Kindle': kindle.md
      - 'Từ điển': dictionary.md
      - 'Youtube': youtube.md
  - 'Immersion':
      - 'Tổng quan': overview.md
      - 'Mass': mass.md
      - 'Active': active.md
      - 'Passive': passive.md
  - 'Mining':
      - 'Đào câu': sentence-mining.md
      - 'Timeboxing': timeboxing.md
  - 'Resources & Recommendations':
      - 'Tài nguyên': 'resources.md'
      - 'Gợi ý khác': 'recommendations.md'


     
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false