site_name: Tu luyện ngoại ngữ - Daihocmo
site_description: Phương pháp học mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.instant
  palette:
    primary: indigo

nav:
  - Home:
      - Khởi đầu: index.md
      - Động lực học: cai-thien-dong-luc.md
      - Để học thật tốt ngoại ngữ: de-hoc-tot-ngoai-ngu.md
  - Guide:
      - Tự học: guide.md
      - Reading: reading.md
      - Comprehension: input.md
      - SRS: srs.md
      - Language Domain: language-domain.md
  - FAQ:
      - 'FAQ': 'faq.md'
  - Immersion:
      - Overview: overview.md
      - Mass: mass.md
      - Active: active.md
      - Passive: passive.md
  - Setup:
      - Anki: anki.md
      - Kindle: kindle.md
      - Dictionary: dictionary.md
  - Mining:
      - Sentence Mining: sentence-mining.md
      - Timeboxing: timeboxing.md
  - Resources & Recommendations:
      - Resources: 'resources.md'
      - Recommendations: 'recommendations.md'


     
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false